### ISSUE TITLE
CPU usage increases

### ISSUE THREAD

**Issue by kasashimaVeeple** [selyunin/bno055_usb_stick_py#4]
I was able to get this driver working on Raspbian(buster) .
Thank you for making BNO055 USB Stick Python driver!

Running this driver will increase the CPU usage of Raspberry-pi and will hinder other processing.
We made following modifications to bno055_usb_stick.py to reduce the CPU usage.
Share information to you.

```
:
:
    def check_streaming_packet(self):
:
:
        if len(self.buffer) != 0x38:
            while len(self.buffer) != 0x38:
                time.sleep(0.01) # -> add
                # pop all the packets from serial buffer
                self.recv()
:
:
```

**Comment by selyunin** [comment]
Hi @kasashimaVeeple!

Thanks for sharing your changes! Great, that you find it useful in your system.
Could you also provide a patch (with ` git format-patch` or send a pull request?

Thanks!

**Comment by selyunin** [comment]
closing an obsolete issue
