### ISSUE TITLE
Raspberry pi support

### ISSUE THREAD

**Issue by shantnavagarwal** [selyunin/bno055_usb_stick_py#5]
I am able to use this library on my laptop running ubuntu. However, I am not able to connect to the bno055 USB stick when using this code on a raspberry pi. I have installed all the dependencies. I am getting the exception "BNO USB stick not connected"

**Comment by selyunin** [comment]
Hi @shantnavagarwal 

It is in general not enough information to pinpoint what exactly goes wrong in your case.

Try to troubleshoot following the instructions from the closed issue, in particularly  starting from this comment:
https://github.com/selyunin/bno055_usb_stick_py/issues/3#issuecomment-502683364

Let me know if it helps.

**Comment by shantnavagarwal** [comment]
Hi, it is working now! I think it is quite important to enter the port while creating the BNO object. 

bno_usb_stick = BnoUsbStick(port=‘/dev/ttyACM0’).

Thanks for the help!
